#! /bin/sh

bspc config border_width        1
bspc config window_gap         30

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config wm_name LG3D

bspc monitor -d i ii iii iv v vi vii viii ix x

bspc rule -a Gimp desktop=^5 follow=on floating=on
bspc rule -a firefox desktop=^2
# bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a feh floating=on manage=off
